#!/bin/sh

CODEREPOS="http://svn.coderepos.org/share/lang/javascript/vimperator-plugins/trunk/"

svn export ${CODEREPOS}"_libly.js"
svn export ${CODEREPOS}"copy.js"
svn export ${CODEREPOS}"direct_bookmark.js"
svn export ${CODEREPOS}"feedSomeKeys_2.js"
svn export ${CODEREPOS}"google-search.js"
svn export ${CODEREPOS}"googlesuggest.js"
svn export ${CODEREPOS}"hatena-bookmark-search.js"
svn export ${CODEREPOS}"hatenabookmark_show.js"
svn export ${CODEREPOS}"ldrize_cooperation.js"
svn export ${CODEREPOS}"lookupDictionary.js"
svn export ${CODEREPOS}"migemized_find.js"
svn export ${CODEREPOS}"migemo_completions.js"
svn export ${CODEREPOS}"migemo_hint.js"
svn export ${CODEREPOS}"proxy.js"
svn export ${CODEREPOS}"uaSwitchLite.js"
svn export ${CODEREPOS}"xpathBlink.js"
